# Generated by Django 5.2.6 on 2025-10-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-timestamp'], 'verbose_name': 'مكالمة', 'verbose_name_plural': 'المكالمات'},
        ),
        migrations.AddField(
            model_name='call',
            name='call_type',
            field=models.CharField(choices=[('audio', 'مكالمة صوتية'), ('video', 'مكالمة فيديو')], default='audio', max_length=10),
        ),
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('initiated', 'تم البدء'), ('ongoing', 'جارية'), ('completed', 'مكتملة'), ('missed', 'فائتة'), ('rejected', 'مرفوضة')], default='initiated', max_length=10),
        ),
    ]
