# Generated by Django 5.2.6 on 2025-10-06 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_onlineuser_roominvitation_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='roominvitation',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roominvitation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='roominvitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='roominvitation',
            unique_together={('room', 'invited_user')},
        ),
    ]
