# Generated by Django 5.2.6 on 2025-10-07 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_roominvitation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineuser',
            options={'verbose_name': 'مستخدم متصل', 'verbose_name_plural': 'المستخدمون المتصلون'},
        ),
        migrations.RemoveField(
            model_name='onlineuser',
            name='channel_name',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='online_users',
            field=models.ManyToManyField(blank=True, related_name='online_rooms', through='chat.OnlineUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineuser',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='onlineuser',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
    ]
